import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/wire-elements/modal/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './vendor/masmerise/livewire-toaster/resources/views/*.blade.php',
    ],
    safelist: [
        {
            pattern: /max-w-(sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)/,
            variants: ['sm', 'md', 'lg', 'xl', '2xl'],
        },
        {
            pattern: /bg-(sky|orange)-(100|200|300|400|500|600|700|800|900)/,
        },
        'bg-gold',
        'bg-silver',
        'bg-bronze',
        'bg-crew-300',
        'bg-crew-500',
        'bg-apricot-peach-500',
        'bg-apricot-peach-300',
        'text-apricot-peach-300',
        'text-apricot-peach-400',
        'text-apricot-peach-500',
        'stroke-apricot-peach-300',
        'stroke-apricot-peach-400',
        'bg-participant-500',
        'bg-participant-700',
        'bg-violet-500',
        'bg-violet-700',
        'hover:from-participant-500',
        'hover:from-participant-600',
        'hover:to-participant-700',
        'hover:to-participant-800',
        'hover:from-violet-500',
        'hover:from-violet-600',
        'hover:to-violet-700',
        'hover:to-violet-800',
        'hover:from-partner-500',
        'hover:from-partner-600',
        'hover:to-partner-700',
        'hover:to-partner-800',
        'hover:from-crew-500',
        'hover:from-crew-600',
        'hover:to-crew-700',
        'hover:to-crew-800',
        'bg-gray-600',
        'bg-apricot-peach-300'
    ],
    theme: {
        extend: {
            fontFamily: {

                sans: ['Inter Var', 'Montserrat', ...defaultTheme.fontFamily.sans],
                'montserrat': ['Montserrat', 'sans-serif'],
            },
            lineHeight: {
                'extra-tight': '1.15',
                '12': '3rem',
            },
            colors: {
                'gradient-yellow': '#F9CD32',
                'gradient-pink': '#A37BB1',
                'gradient-purple': '#7533A9',
                'gradient-blue': '#3666FF',
                'gradient-light-blue': '#61B7FF',
                'gradient-dark-blue': '#3666E6',
                'gradient-light-pink': '#EDDEF0',
                'gradient-dark-pink': '#A37BB1',
                'gold': '#FFD700',
                'silver': '#C0C0C0',
                'bronze': '#CD7F32',
                'crew': {
                    '50': '#fff8eb',
                    '100': '#ffebc6',
                    '200': '#ffd388',
                    '300': '#ffb74a',
                    '400': '#ff9919',
                    '500': '#f97707',
                    '600': '#dd5302',
                    '700': '#b73606',
                    '800': '#94290c',
                    '900': '#7a220d',
                    '950': '#460f02',
                },
                'participant': {
                    '50': '#eef4ff',
                    '100': '#d9e5ff',
                    '200': '#bcd2ff',
                    '300': '#8eb5ff',
                    '400': '#598dff',
                    '500': '#3666ff',
                    '600': '#1b40f5',
                    '700': '#142de1',
                    '800': '#1726b6',
                    '900': '#19268f',
                    '950': '#141a57',
                },
                'partner': {
                    '50': '#fbf6fd',
                    '100': '#f6ebfc',
                    '200': '#edd7f7',
                    '300': '#e0b7f0',
                    '400': '#ce8ce6',
                    '500': '#b862d6',
                    '600': '#9c40b9',
                    '700': '#833299',
                    '800': '#6c2b7d',
                    '900': '#5c2867',
                    '950': '#390f43',
                },
                'apricot-peach': {
                    '50': '#fdf5ef',
                    '100': '#fbe6da',
                    '200': '#f5cbb3',
                    '300': '#eea883',
                    '400': '#e77a50',
                    '500': '#e1582e',
                    '600': '#d24124',
                    '700': '#af301f',
                    '800': '#8b2921',
                    '900': '#71251d',
                    '950': '#3d100d',
                },
            }
        },
    },
    darkMode: 'class',
    plugins: [forms, typography],
};
