# The YML file format allows for comments to be added to the file.
# This makes it possible to add explanations to the file.
# The roles are defined in the roles section of the file.
roles:
  - participant               # Users that can participate to presentations and workshops
  - company representative    # Company representatives
  - company member            # Company members
  - event organizer           # Crew member - Manages the Schedule, Users, Editions, Companies, Sponsorships, Presentations and Booths
  - assistant organizer       # Crew member - Like the event organizer, but without the Schedule and Editions
  - company market supervisor # Crew member - Manages Booths
  - speakers supervisor       # Crew member - Manages Presentations
  - pr lead                   # Crew member - Posting announcements to feed.
  - entertainment organizer   # Crew member - TBD
  - booth owner               # Booth owner - responsible for the booth of the company
  - pending speaker           # Pending speaker - temporary role for the speaker permissions
  - pending booth owner       # Pending booth owner - temporary role for the booth owner permissions

permissions:
  booth:
    viewAny: [ event organizer, assistant organizer, company market supervisor ]
    view: [ event organizer, assistant organizer, company market supervisor, booth owner ]
    create: [ event organizer, assistant organizer ]
    update: [ event organizer, assistant organizer, booth owner ]
    delete: [ event organizer, assistant organizer ]
  booth request:
    create: [ company representative, company member, pending booth owner ]
    view: [ company representative, event organizer, assistant organizer, company market supervisor, company member,
            booth owner, pending booth owner ]
    approve: [ event organizer, assistant organizer ]
  company:
    viewAny: [ event organizer, assistant organizer ]
    view: [ event organizer, assistant organizer, company representative, company member, booth owner, pending speaker,
            pending booth owner ]
    create: [ event organizer, assistant organizer ]
    update: [ event organizer, assistant organizer, company representative ]
    delete: [ event organizer, assistant organizer ]
  company request:
    view: [ company representative, event organizer, assistant organizer ]
    update: [ event organizer, assistant organizer ]
  company delete request:
    create: company representative
    view: [ event organizer, assistant organizer, company representative ]
  company member:
    viewAny: [ event organizer, assistant organizer, company representative, company member, booth owner, pending speaker ]
    update: company representative
    delete: company representative
    add: event organizer
  company member invitation:
    viewAny: company representative
    create: company representative
    delete: company representative
  crew:
    invite: [ event organizer, assistant organizer ]
    update: [ event organizer, assistant organizer ]
    viewAny: [ event organizer, assistant organizer, company market supervisor, speakers supervisor, pr lead,
               entertainment organizer ]
    remove: [ event organizer ]
  presentation:
    viewAny: [ event organizer, assistant organizer, speakers supervisor ]
    view: [ event organizer, assistant organizer, speakers supervisor, participant, company representative,
            company member, pending speaker ]
    create: [ event organizer, assistant organizer, speakers supervisor ]
    update: [ event organizer, assistant organizer, speakers supervisor, participant ]
    delete: [ event organizer, assistant organizer, participant ]
    enroll: participant
  presentation request:
    create: [ participant, company representative ]
    view: [ company representative, event organizer, assistant organizer, speakers supervisor ]
    update: [ event organizer, assistant organizer ]
  presentation participants:
    view: [ event organizer, assistant organizer, speakers supervisor ]
  room:
    viewAny: [ event organizer, assistant organizer ]
    view: [ event organizer, assistant organizer ]
    create: [ event organizer, assistant organizer ]
    update: [ event organizer, assistant organizer ]
    delete: [ event organizer, assistant organizer ]
  schedule:
    view: [ event organizer, assistant organizer ]
    update: event organizer
  sponsorship:
    viewAny: [ event organizer, assistant organizer ]
    view: [ event organizer, assistant organizer ]
    create: [ event organizer, assistant organizer ]
    delete: [ event organizer, assistant organizer ]
  sponsorship request:
    view: [ company representative, event organizer, assistant organizer ]
    create: company representative
    update: [ event organizer, assistant organizer ]
  edition:
    viewAny: event organizer
    view: event organizer
    create: event organizer
    update: event organizer
    delete: event organizer
    activate: event organizer
  user:
    viewAny: event organizer
  frequent question:
    viewAny: [ event organizer, assistant organizer ]
    view: [ event organizer, assistant organizer ]
    create: [ event organizer, assistant organizer ]
    delete: [ event organizer, assistant organizer ]
  feedback:
    viewAny: event organizer
    view: event organizer
