# The YML file format allows for comments to be added to the file.
# This makes it possible to add explanations to the file.
# The roles are defined in the roles section of the file.
roles:
  - participant # Users that can participate to presentations and workshops
  - companyrep  # Company representatives
  - companymem  # Company members
  - crew        # Members of the event organisation crew
  - speaker
  - booth owner

#TODO update to match roles below to roles above
permissions:
  booth:
    viewAny: crew
    view: crew
    create: crew
    edit: crew
    delete: crew
  booth request:
    create: companyrep
    view: [ companyrep, crew ]
    approve: crew
  company:
    viewAny: crew
    view: [ crew, companyrep, companymem ]
    create: crew
    edit: [ crew, companyrep ]
    delete: crew
  company request:
    view: [ companyrep, crew ]
    edit: crew
  company delete request:
    create: companyrep
    view: [ crew, companyrep ]
  company member:
    viewAny: [ crew, companyrep, companymem ]
    update: companyrep
    delete: companyrep
  company member invitation:
    viewAny: companyrep
    create: companyrep
    delete: companyrep
  crew:
    invite: crew
    edit: crew
  presentation list:
    view: crew
  presentation:
    viewAny: crew
    view: [ crew, speaker ]
    create: crew
    update: [ crew, speaker ]
    delete: [ crew, speaker ]
    enroll: participant
  presentation request:
    create: [ participant, companyrep ]
    view: [ speaker, companyrep, crew ]
    update: crew
  presentation participants:
    view: crew
  room:
    viewAny: crew
    view: crew
    create: crew
    update: crew
    delete: crew
  schedule:
    view: crew
    update: crew
  sponsorship:
    viewAny: crew
    view: crew
    create: crew
    delete: crew
  sponsorship request:
    view: [ companyrep, crew ]
    create: companyrep
    update: crew
