name: Audit
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  composer_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install Composer
        run: composer install --no-progress --prefer-dist

      - name: Audit Composer dependencies
        run: composer audit --no-interaction
  npm_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@3
        with:
          node-version: '20'

      - name: Install npm
        run: npm install

      - name: Audit npm dependencies
        run: npm audit

