name: PHPCS

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.php'
      - 'phpcs.xml'
      - '.github/workflows/phpcs.yml'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Dependencies
        run: composer install

      - name: PHPCS check
        uses: navarr/phpcs-action@v3
        with:
          only_changed_files: true
