name: Static analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.php'
      - 'phpcs.xml'
      - 'static-analysis.yml'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHPCS check
        uses: navarr/phpcs-action@v3
        with:
          only_changed_files: true
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse --configuration=phpstan.neon
